version: '3.8'

services:
  mysql-db:
    image: mysql:8.0   # better to lock a stable version, not latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: has@2004
      MYSQL_DATABASE: project
      # MYSQL_USER: root
      # MYSQL_PASSWORD: has@2004
    ports:
      - "3307:3306"    # local 3307 → container 3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  backend:
    build: ./backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: has@2004
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy   # wait for mysql-db to be healthy before starting backend

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
